name: client
description: A sample web application
dependencies:
  browser: any
transformers: 
- $dart2js:
    checked: true
    minify: true
    verbose: true
    environment: {name: value, ...}
    analyzeAll: true
    suppressWarnings: true
    suppressHints: true
    terse: true
    csp: true