#ifndef _CLIFF_PLATFORM_INDEPENDENCE_CONSOLE_HEADER_H
#define _CLIFF_PLATFORM_INDEPENDENCE_CONSOLE_HEADER_H

#include "cliff/platform_independence/Header.h"

namespace CLIFF {


	enum ConsoleTextColor {
		CONSOLE_TEXT_COLOR_WHITE,
		CONSOLE_TEXT_COLOR_BLACK,
		CONSOLE_TEXT_COLOR_RED,
		CONSOLE_TEXT_COLOR_GREEN,
		CONSOLE_TEXT_COLOR_BLUE
	};

	enum ConsoleBackgroundColor {
		CONSOLE_BACKGROUND_COLOR_WHITE,
		CONSOLE_BACKGROUND_COLOR_BLACK,
		CONSOLE_BACKGROUND_COLOR_RED,
		CONSOLE_BACKGROUND_COLOR_GREEN,
		CONSOLE_BACKGROUND_COLOR_BLUE
	};

}

#endif
